selected_ids = [
    'psf__requests-1724', 
    'django__django-15161', 
    'pydata__xarray-4966', 
    'django__django-14170', 
    'django__django-11149', 
    'django__django-11206', 
    'sympy__sympy-23824', 
    'sphinx-doc__sphinx-8595', 
    'sphinx-doc__sphinx-9658', 
    'django__django-16136', 
    'django__django-12193', 
    'sympy__sympy-23950', 
    'django__django-16263', 
    'pydata__xarray-3305', 
    'pydata__xarray-6461', 
    'django__django-15957', 
    'scikit-learn__scikit-learn-25102', 
    'sphinx-doc__sphinx-8459', 
    'sphinx-doc__sphinx-7757', 
    'django__django-16502', 
    'django__django-11138', 
    'scikit-learn__scikit-learn-12973', 
    'scikit-learn__scikit-learn-14053', 
    'matplotlib__matplotlib-24570', 
    'matplotlib__matplotlib-24870', 
    'django__django-13820', 
    'django__django-16801', 
    'matplotlib__matplotlib-20826', 
    'sympy__sympy-16886', 
    'sphinx-doc__sphinx-8593', 
    'django__django-13279', 
    'astropy__astropy-7671', 
    'pylint-dev__pylint-4661', 
    'django__django-10097', 
    'pydata__xarray-7229', 
    'scikit-learn__scikit-learn-13496', 
    'sympy__sympy-15599', 
    'django__django-11087', 
    'sympy__sympy-13372', 
    'django__django-14765', 
    'django__django-11451', 
    'django__django-17029', 
    'sympy__sympy-12481', 
    'django__django-13158', 
    'matplotlib__matplotlib-24026', 
    'sphinx-doc__sphinx-8120', 
    'astropy__astropy-8707', 
    'scikit-learn__scikit-learn-11578', 
    'scikit-learn__scikit-learn-14629', 
    'django__django-12774', 
    'matplotlib__matplotlib-14623', 
    'django__django-15277', 
    'matplotlib__matplotlib-25332', 
    'scikit-learn__scikit-learn-13142', 
    'django__django-14771', 
    'pytest-dev__pytest-7205', 
    'sympy__sympy-13798', 
    'django__django-11734', 
    'django__django-11099', 
    'sympy__sympy-18698', 
    'django__django-16100', 
    'sympy__sympy-15976', 
    'scikit-learn__scikit-learn-10908', 
    'sympy__sympy-15345', 
    'django__django-14007', 
    'django__django-12713', 
    'sympy__sympy-16450', 
    'django__django-16877', 
    'astropy__astropy-14508', 
    'sphinx-doc__sphinx-10673', 
    'django__django-13807', 
    'django__django-14915', 
    'pydata__xarray-6744', 
    'django__django-13315', 
    'django__django-16527', 
    'sympy__sympy-20916', 
    'django__django-14534', 
    'django__django-13012', 
    'django__django-13212', 
    'django__django-15732', 
    'pydata__xarray-4075', 
    'matplotlib__matplotlib-23314', 
    'scikit-learn__scikit-learn-12585', 
    'pylint-dev__pylint-8898', 
    'django__django-11265', 
    'sphinx-doc__sphinx-8638', 
    'sympy__sympy-12096', 
    'django__django-12125', 
    'sympy__sympy-17139', 
    'django__django-13964', 
    'sympy__sympy-13480', 
    'sphinx-doc__sphinx-10323', 
    'django__django-11885', 
    'matplotlib__matplotlib-26466', 
    'sympy__sympy-24661', 
    'django__django-13417', 
    'sphinx-doc__sphinx-8721', 
    'django__django-13837', 
    'django__django-15554', 
    'django__django-13794',
    'sphinx-doc__sphinx-7462', 
    'django__django-13551', 
    'sphinx-doc__sphinx-9320', 
    'sympy__sympy-13878', 
    'pytest-dev__pytest-7571', 
    'django__django-15103', 
    'django__django-16662', 
    'django__django-15022', 
    'sympy__sympy-13615', 
    'django__django-15916', 
    'pallets__flask-5014', 
    'pylint-dev__pylint-6903', 
    'scikit-learn__scikit-learn-14894', 
    'django__django-15382', 
    'pydata__xarray-2905', 
    'pylint-dev__pylint-4604', 
    'django__django-12858', 
    'django__django-14608', 
    'django__django-7530', 
    'django__django-13195', 
    'django__django-13449', 
    'sympy__sympy-22714', 
    'sympy__sympy-16766', 
    'sphinx-doc__sphinx-9367', 
    'matplotlib__matplotlib-25775'
]