selected_ids = [
    "astropy__astropy-12907",
    "astropy__astropy-14365",
    "django__django-10914",
    "django__django-10924",
    "django__django-11001",
    "django__django-11049",
    "django__django-11133",
    "django__django-11179",
    "django__django-11422",
    "django__django-11742",
    "django__django-11797",
    "django__django-11815",
    "django__django-11848",
    "django__django-11999",
    "django__django-12113",
    "django__django-12184",
    "django__django-12284",
    "django__django-12453",
    "django__django-12708",
    "django__django-12856",
    "django__django-13401",
    "django__django-13447",
    "django__django-13551",
    "django__django-13658",
    "django__django-13660",
    "django__django-13757",
    "django__django-13768",
    "django__django-13964",
    "django__django-14155",
    "django__django-14238",
    "django__django-14534",
    "django__django-14580",
    "django__django-14608",
    "django__django-15061",
    "django__django-15320",
    "django__django-15814",
    "django__django-15851",
    "django__django-15902",
    "django__django-16046",
    "django__django-16379",
    "django__django-16595",
    "django__django-16820",
    "matplotlib__matplotlib-23299",
    "matplotlib__matplotlib-23314",
    "matplotlib__matplotlib-23913",
    "matplotlib__matplotlib-25311",
    "matplotlib__matplotlib-25433",
    "matplotlib__matplotlib-26011",
    "pallets__flask-4045",
    "pallets__flask-4992",
    "psf__requests-2317",
    "pydata__xarray-4493",
    "pydata__xarray-5131",
    "pylint-dev__pylint-5859",
    "pylint-dev__pylint-6506",
    "pytest-dev__pytest-11148",
    "pytest-dev__pytest-5227",
    "pytest-dev__pytest-5692",
    "pytest-dev__pytest-7220",
    "scikit-learn__scikit-learn-10297",
    "scikit-learn__scikit-learn-10949",
    "scikit-learn__scikit-learn-13439",
    "scikit-learn__scikit-learn-13496",
    "scikit-learn__scikit-learn-13497",
    "scikit-learn__scikit-learn-14087",
    "scikit-learn__scikit-learn-14092",
    "scikit-learn__scikit-learn-14983",
    "scikit-learn__scikit-learn-15512",
    "scikit-learn__scikit-learn-25747",
    "sphinx-doc__sphinx-10451",
    "sphinx-doc__sphinx-11445",
    "sphinx-doc__sphinx-7975",
    "sphinx-doc__sphinx-8273",
    "sphinx-doc__sphinx-8282",
    "sphinx-doc__sphinx-8435",
    "sphinx-doc__sphinx-8474",
    "sphinx-doc__sphinx-8595",
    "sphinx-doc__sphinx-8721",
    "sympy__sympy-12171",
    "sympy__sympy-12454",
    "sympy__sympy-13437",
    "sympy__sympy-13915",
    "sympy__sympy-13971",
    "sympy__sympy-14317",
    "sympy__sympy-16106",
    "sympy__sympy-16792",
    "sympy__sympy-16988",
    "sympy__sympy-17630",
    "sympy__sympy-18698",
    "sympy__sympy-19007",
    "sympy__sympy-19254",
    "sympy__sympy-20049",
    "sympy__sympy-21055",
    "sympy__sympy-21171",
    "sympy__sympy-22714",
    "sympy__sympy-22840",
    "sympy__sympy-23117",
    "sympy__sympy-24102",
    "sympy__sympy-24152",
    "sympy__sympy-24213"
]