selected_ids = [
    'sphinx-doc__sphinx-9461', 
    'django__django-15375', 
    'django__django-17084', 
    'scikit-learn__scikit-learn-12682', 
    'astropy__astropy-7166', 
    'django__django-14631', 
    'sympy__sympy-23413', 
    'astropy__astropy-13033', 
    'sphinx-doc__sphinx-10614', 
    'django__django-12406', 
    'django__django-11749', 
    'django__django-16899', 
    'sphinx-doc__sphinx-8551', 
    'scikit-learn__scikit-learn-9288', 
    'django__django-13741', 
    'django__django-15814', 
    'sympy__sympy-21379', 
    'django__django-16139', 
    'django__django-14376', 
    'sympy__sympy-15875', 
    'django__django-13821', 
    'psf__requests-2931', 
    'pylint-dev__pylint-4970', 
    'django__django-13925', 
    'django__django-11964', 
    'pydata__xarray-3677', 
    'django__django-13363', 
    'astropy__astropy-14309', 
    'sphinx-doc__sphinx-10466', 
    'matplotlib__matplotlib-25122', 
    'django__django-14434', 
    'pytest-dev__pytest-10051', 
    'pytest-dev__pytest-7324', 
    'scikit-learn__scikit-learn-10297', 
    'scikit-learn__scikit-learn-26323', 
    'django__django-11400', 
    'django__django-12039', 
    'sympy__sympy-13852', 
    'django__django-14311', 
    'django__django-13109', 
    'sympy__sympy-15809', 
    'sphinx-doc__sphinx-11510', 
    'django__django-15127', 
    'django__django-13590', 
    'django__django-11820', 
    'django__django-16485', 
    'django__django-13786', 
    'django__django-12325', 
    'django__django-16145', 
    'django__django-12209', 
    'django__django-13297', 
    'sympy__sympy-13091', 
    'sphinx-doc__sphinx-8548', 
    'astropy__astropy-14369', 
    'django__django-15851', 
    'sympy__sympy-16792', 
    'django__django-12276', 
    'scikit-learn__scikit-learn-13124', 
    'sympy__sympy-15017', 
    'django__django-16082', 
    'django__django-13568', 
    'pytest-dev__pytest-7432', 
    'django__django-13512', 
    'sphinx-doc__sphinx-8475', 
    'django__django-16256', 
    'pylint-dev__pylint-7080', 
    'django__django-13410', 
    'pytest-dev__pytest-10356', 
    'django__django-14238', 
    'sympy__sympy-23534', 
    'django__django-12262', 
    'matplotlib__matplotlib-26113', 
    'django__django-13513', 
    'django__django-15563', 
    'django__django-15380', 
    'django__django-16612', 
    'pytest-dev__pytest-6197', 
    'django__django-12965', 
    'sympy__sympy-19346', 
    'matplotlib__matplotlib-22871', 
    'django__django-13569', 
    'django__django-14855', 
    'sympy__sympy-20801', 
    'django__django-11095', 
    'django__django-15280', 
    'django__django-14787', 
    'django__django-15037', 
    'django__django-15252', 
    'django__django-14351', 
    'django__django-14053', 
    'sphinx-doc__sphinx-9229', 
    'sympy__sympy-24066', 
    'sympy__sympy-13974', 
    'scikit-learn__scikit-learn-25973', 
    'django__django-11333', 
    'django__django-15499', 
    'pytest-dev__pytest-5840', 
    'django__django-12741', 
    'sphinx-doc__sphinx-8265', 
    'sympy__sympy-19783', 
    'django__django-13089', 
    'sympy__sympy-19954', 
    'scikit-learn__scikit-learn-26194', 
    'psf__requests-1921', 
    'scikit-learn__scikit-learn-11310', 
    'astropy__astropy-14365', 
    'sphinx-doc__sphinx-7440', 
    'pydata__xarray-7233', 
    'sympy__sympy-20154', 
    'pytest-dev__pytest-7490', 
    'django__django-14034', 
    'sphinx-doc__sphinx-9602', 
    'django__django-11211', 
    'sympy__sympy-24443', 
    'sphinx-doc__sphinx-8269', 
    'astropy__astropy-7336', 
    'django__django-12155', 
    'django__django-16631', 
    'django__django-12143', 
    'astropy__astropy-7606', 
    'sympy__sympy-21612', 
    'django__django-15731', 
    'django__django-14493', 
    'django__django-10880', 
    'sphinx-doc__sphinx-10449'
]