selected_ids = [
    "astropy__astropy-14182",
    "astropy__astropy-14995",
    "astropy__astropy-7606",
    "django__django-10880",
    "django__django-11119",
    "django__django-11133",
    "django__django-11138",
    "django__django-11239",
    "django__django-11265",
    "django__django-11740",
    "django__django-11848",
    "django__django-12406",
    "django__django-12419",
    "django__django-12708",
    "django__django-12741",
    "django__django-13023",
    "django__django-13028",
    "django__django-13089",
    "django__django-13109",
    "django__django-13279",
    "django__django-13297",
    "django__django-13363",
    "django__django-13670",
    "django__django-13794",
    "django__django-13964",
    "django__django-14007",
    "django__django-14140",
    "django__django-14155",
    "django__django-14404",
    "django__django-14559",
    "django__django-14752",
    "django__django-14855",
    "django__django-15098",
    "django__django-15128",
    "django__django-15277",
    "django__django-15503",
    "django__django-15569",
    "django__django-15731",
    "django__django-15851",
    "django__django-16333",
    "django__django-16661",
    "django__django-16877",
    "django__django-16950",
    "django__django-17087",
    "django__django-9296",
    "matplotlib__matplotlib-22865",
    "matplotlib__matplotlib-22871",
    "matplotlib__matplotlib-23314",
    "matplotlib__matplotlib-24177",
    "matplotlib__matplotlib-24570",
    "matplotlib__matplotlib-26208",
    "mwaskom__seaborn-3187",
]
