selected_ids = [
    'django__django-14539', 
    'django__django-11133', 
    'django__django-11551', 
    'django__django-15103', 
    'sympy__sympy-24213', 
    'django__django-11265', 
    'django__django-11119', 
    'django__django-12663', 
    'django__django-15930', 
    'sympy__sympy-20801', 
    'django__django-14373', 
    'scikit-learn__scikit-learn-14894',
    'pylint-dev__pylint-6386', 
    'scikit-learn__scikit-learn-25931', 
    'pydata__xarray-3677', 
    'django__django-16429', 
    'scikit-learn__scikit-learn-14141', 
    'django__django-13807', 
    'sphinx-doc__sphinx-7889', 
    'matplotlib__matplotlib-25122', 
    'django__django-11964', 
    'sphinx-doc__sphinx-8459', 
    'django__django-12276', 
    'django__django-11066', 
    'scikit-learn__scikit-learn-10908', 
    'sympy__sympy-22456', 
    'django__django-15561', 
    'django__django-15741', 
    'django__django-14376', 
    'django__django-12713', 
    'sphinx-doc__sphinx-9658', 
    'django__django-15569', 
    'astropy__astropy-7336', 
    'sympy__sympy-12096', 
    'django__django-12050', 
    'astropy__astropy-12907', 
    'django__django-11951', 
    'sphinx-doc__sphinx-9698', 
    'django__django-13551', 
    'sympy__sympy-19783', 
    'scikit-learn__scikit-learn-10297', 
    'django__django-15916', 
    'pydata__xarray-2905', 
    'sympy__sympy-13757', 
    'psf__requests-1921', 
    'sympy__sympy-19346', 
    'scikit-learn__scikit-learn-13135', 
    'sympy__sympy-23950', 
    'django__django-15278', 
    'sphinx-doc__sphinx-9320', 
    'pydata__xarray-3095', 
    'django__django-13089', 
    'sympy__sympy-20154', 
    'django__django-14771', 
    'django__django-14238', 
    'django__django-15037', 
    'sympy__sympy-19954', 
    'django__django-11179', 
    'sympy__sympy-24443', 
    'sphinx-doc__sphinx-8475', 
    'sympy__sympy-24661', 
    'django__django-15987', 
    'astropy__astropy-8872', 
    'django__django-12708', 
    'sympy__sympy-18189', 
    'django__django-10914', 
    'sympy__sympy-22914', 
    'django__django-10973', 
    'django__django-15863', 
    'django__django-13590', 
    'django__django-7530', 
    'pydata__xarray-4094', 
    'django__django-14580', 
    'scikit-learn__scikit-learn-25102', 
    'pydata__xarray-4966', 
    'django__django-11490', 
    'django__django-14787', 
    'django__django-13449', 
    'django__django-16819', 
    'django__django-13741', 
    'django__django-16899', 
    'django__django-14915', 
    'pytest-dev__pytest-5262', 
    'pydata__xarray-6461', 
    'psf__requests-1142', 
    'django__django-12774', 
    'django__django-14122', 
    'django__django-16493', 
    'django__django-16255', 
    'django__django-14999', 
    'django__django-16315', 
    'sphinx-doc__sphinx-10673', 
    'django__django-11099', 
    'django__django-13658', 
    'sympy__sympy-20590', 
    'django__django-12209', 
    'django__django-11276', 
    'scikit-learn__scikit-learn-14710', 
    'django__django-17087', 
    'django__django-13670'
]