selected_ids = [
    'django__django-11141', 
    'django__django-11603', 
    'django__django-14725', 
    'django__django-15572', 
    'django__django-11119', 
    'django__django-14140', 
    'django__django-14011', 
    'astropy__astropy-8872', 
    'sympy__sympy-17630', 
    'django__django-16667', 
    'django__django-15467', 
    'django__django-16642', 
    'astropy__astropy-13236', 
    'pytest-dev__pytest-7236', 
    'django__django-14500', 
    'sphinx-doc__sphinx-7985', 
    'sphinx-doc__sphinx-10435', 
    'django__django-11740', 
    'sphinx-doc__sphinx-7590', 
    'django__django-10999', 
    'pytest-dev__pytest-7521', 
    'django__django-13121', 
    'django__django-14017', 
    'sphinx-doc__sphinx-9673', 
    'pydata__xarray-4687', 
    'scikit-learn__scikit-learn-25747', 
    'matplotlib__matplotlib-26208', 
    'sympy__sympy-13031', 
    'pydata__xarray-4094', 
    'sphinx-doc__sphinx-9698', 
    'django__django-14155', 
    'django__django-13344', 
    'matplotlib__matplotlib-22719', 
    'psf__requests-2317', 
    'sympy__sympy-20590', 
    'django__django-16454', 
    'pylint-dev__pylint-6386', 
    'sympy__sympy-14248', 
    'sphinx-doc__sphinx-7748', 
    'django__django-11532', 
    'django__django-16661', 
    'matplotlib__matplotlib-23299', 
    'sympy__sympy-21596', 
    'django__django-15128', 
    'matplotlib__matplotlib-26291', 
    'astropy__astropy-14182', 
    'django__django-9296', 
    'django__django-14559', 
    'pydata__xarray-3993', 
    'django__django-15503', 
    'sympy__sympy-15349', 
    'django__django-11848', 
    'scikit-learn__scikit-learn-10844', 
    'django__django-13516', 
    'scikit-learn__scikit-learn-14983', 
    'django__django-11477', 
    'django__django-13401', 
    'sympy__sympy-19495', 
    'sympy__sympy-18199', 
    'sympy__sympy-18189', 
    'sphinx-doc__sphinx-9591', 
    'django__django-16901', 
    'django__django-11728', 
    'django__django-15104', 
    'django__django-15987', 
    'django__django-12304', 
    'django__django-11951', 
    'django__django-14999', 
    'mwaskom__seaborn-3069', 
    'django__django-14349', 
    'django__django-15973', 
    'pydata__xarray-3095', 
    'sympy__sympy-22914', 
    'django__django-16116', 
    'django__django-11880', 
    'scikit-learn__scikit-learn-14496', 
    'django__django-11163', 
    'django__django-10554', 
    'django__django-10914', 
    'pytest-dev__pytest-10081', 
    'django__django-12308', 
    'sphinx-doc__sphinx-9258', 
    'psf__requests-5414', 
    'sympy__sympy-13647', 
    'sympy__sympy-18763', 
    'django__django-11815', 
    'django__django-14539', 
    'sympy__sympy-13877', 
    'astropy__astropy-12907', 
    'django__django-14404', 
    'sympy__sympy-11618', 
    'mwaskom__seaborn-3187', 
    'scikit-learn__scikit-learn-14710', 
    'django__django-14672', 
    'sympy__sympy-24562', 
    'pydata__xarray-6721', 
    'pydata__xarray-6938', 
    'astropy__astropy-13398', 
    'django__django-16493', 
    'scikit-learn__scikit-learn-14087', 
    'sphinx-doc__sphinx-8035', 
    'astropy__astropy-14598', 
    'pytest-dev__pytest-5631', 
    'django__django-16819', 
    'django__django-14792', 
    'sympy__sympy-17655', 
    'django__django-14315', 
    'pydata__xarray-6992', 
    'django__django-13346', 
    'django__django-11433', 
    'sphinx-doc__sphinx-9711', 
    'astropy__astropy-14539', 
    'sympy__sympy-19040', 
    'scikit-learn__scikit-learn-13779', 
    'sympy__sympy-20428', 
    'django__django-16315', 
    'django__django-11066', 
    'sympy__sympy-24213', 
    'matplotlib__matplotlib-13989', 
    'django__django-12050', 
    'django__django-11555', 
    'scikit-learn__scikit-learn-15100', 
    'sympy__sympy-14531', 
    'matplotlib__matplotlib-22865', 
    'django__django-12419'
]