selected_ids = [
    "django__django-12284",
    "django__django-11910",
    "django__django-12125",
    "django__django-11999",
    "django__django-11848",
    "django__django-11630",
    "django__django-11283",
    "django__django-11049",
    "django__django-10914",
    "astropy__astropy-14365",
    "astropy__astropy-14995",
    "astropy__astropy-7746",
    "django__django-11019",
    "django__django-11001",
    "django__django-11179",
    "django__django-11422",
    "astropy__astropy-6938",
    "astropy__astropy-14182",
    "django__django-11564",
    "django__django-11039",
    "astropy__astropy-12907",
    "django__django-10924",
    "django__django-11583",
    "django__django-11620",
    "django__django-11905",
    "django__django-11797",
    "django__django-11964",
    "django__django-11742",
    "django__django-11815",
    "django__django-12453",
    "django__django-12589",
    "django__django-12700",
    "django__django-13230",
    "django__django-12113",
    "django__django-12708",
    "django__django-12856",
    "django__django-13033",
    "django__django-13315",
    "django__django-13551",
    "django__django-13321",
    "django__django-13660",
    "django__django-13933",
    "django__django-13925",
    "django__django-13710",
    "django__django-14017",
    "django__django-13964",
    "django__django-14155",
    "django__django-14238",
    "django__django-14730",
    "django__django-14534",
    "django__django-14787",
    "django__django-14752",
    "django__django-14855",
    "django__django-14915",
    "django__django-15252",
    "django__django-14999",
    "django__django-15202",
    "django__django-15320",
    "django__django-15498",
    "django__django-15781",
    "django__django-15789",
    "django__django-15814",
    "django__django-15388",
    "django__django-15738",
    "django__django-15996",
    "django__django-16041",
    "django__django-15819",
    "django__django-16229",
    "django__django-16046",
    "django__django-16527",
    "django__django-16408",
    "django__django-16595",
    "django__django-16820",
    "django__django-17051",
    "django__django-17087",
    "matplotlib__matplotlib-18869",
    "matplotlib__matplotlib-23476",
    "matplotlib__matplotlib-22711",
    "matplotlib__matplotlib-23299",
    "matplotlib__matplotlib-23563",
    "matplotlib__matplotlib-23964",
    "matplotlib__matplotlib-23987",
    "matplotlib__matplotlib-24334",
    "matplotlib__matplotlib-25311",
    "matplotlib__matplotlib-25442",
    "mwaskom__seaborn-3010",
    "mwaskom__seaborn-3190",
    "matplotlib__matplotlib-25498",
    "matplotlib__matplotlib-26011",
    "mwaskom__seaborn-2848",
    "psf__requests-2674",
    "pallets__flask-4045",
    "pallets__flask-4992",
    "pallets__flask-5063",
    "mwaskom__seaborn-3407",
    "matplotlib__matplotlib-25332",
    "psf__requests-1963",
    "psf__requests-2148",
    "matplotlib__matplotlib-23314",
    "matplotlib__matplotlib-24149",
]