selected_ids = [
    'matplotlib__matplotlib-24637', 
    'sympy__sympy-22456', 
    'django__django-12663', 
    'matplotlib__matplotlib-23476', 
    'sympy__sympy-20438', 
    'sympy__sympy-13551', 
    'django__django-13343', 
    'pylint-dev__pylint-4551', 
    'sympy__sympy-16597', 
    'pytest-dev__pytest-5809', 
    'sphinx-doc__sphinx-9230', 
    'sphinx-doc__sphinx-8621', 
    'matplotlib__matplotlib-25311', 
    'matplotlib__matplotlib-25960', 
    'scikit-learn__scikit-learn-25232', 
    'pydata__xarray-4629', 
    'matplotlib__matplotlib-24177', 
    'matplotlib__matplotlib-25287', 
    'matplotlib__matplotlib-20859', 
    'sphinx-doc__sphinx-8056', 
    'django__django-11276', 
    'django__django-14580', 
    'django__django-11239', 
    'psf__requests-6028', 
    'django__django-13033', 
    'django__django-12708', 
    'scikit-learn__scikit-learn-25931', 
    'django__django-16429', 
    'astropy__astropy-14096', 
    'django__django-13128', 
    'pydata__xarray-7393', 
    'matplotlib__matplotlib-20488', 
    'django__django-16255', 
    'pytest-dev__pytest-5787', 
    'django__django-15525', 
    'django__django-15098', 
    'django__django-13933', 
    'matplotlib__matplotlib-21568', 
    'astropy__astropy-13579', 
    'matplotlib__matplotlib-25479', 
    'django__django-13670', 
    'django__django-16560', 
    'django__django-13023', 
    'django__django-15278', 
    'pytest-dev__pytest-8399', 
    'psf__requests-1766', 
    'django__django-15741', 
    'sympy__sympy-13757', 
    'pylint-dev__pylint-7277', 
    'django__django-11790', 
    'sphinx-doc__sphinx-7454', 
    'sympy__sympy-17318', 
    'scikit-learn__scikit-learn-14141', 
    'django__django-15629', 
    'matplotlib__matplotlib-24149', 
    'django__django-13028', 
    'astropy__astropy-14995', 
    'sphinx-doc__sphinx-7889', 
    'django__django-16569', 
    'django__django-15561', 
    'django__django-11999', 
    'sympy__sympy-18211', 
    'matplotlib__matplotlib-24627', 
    'django__django-12754', 
    'scikit-learn__scikit-learn-13328', 
    'sphinx-doc__sphinx-7910', 
    'pylint-dev__pylint-6528', 
    'django__django-14752', 
    'pytest-dev__pytest-6202', 
    'django__django-16950', 
    'matplotlib__matplotlib-23412', 
    'django__django-16595', 
    'pydata__xarray-4356', 
    'django__django-11551', 
    'django__django-14373', 
    'django__django-15315', 
    'django__django-11292', 
    'django__django-15863', 
    'django__django-12273', 
    'django__django-13809', 
    'django__django-17087', 
    'pytest-dev__pytest-5262', 
    'pydata__xarray-4695', 
    'pydata__xarray-3151', 
    'sympy__sympy-23262', 
    'scikit-learn__scikit-learn-13135', 
    'django__django-16938', 
    'scikit-learn__scikit-learn-13439', 
    'matplotlib__matplotlib-20676', 
    'django__django-11299', 
    'sympy__sympy-12489', 
    'sphinx-doc__sphinx-11445', 
    'django__django-15569', 
    'matplotlib__matplotlib-24970', 
    'django__django-14089', 
    'django__django-13406', 
    'astropy__astropy-13453', 
    'psf__requests-1142', 
    'astropy__astropy-13977', 
    'django__django-13112', 
    'pytest-dev__pytest-7982', 
    'matplotlib__matplotlib-26342', 
    'django__django-14122', 
    'django__django-15368', 
    'django__django-11179', 
    'django__django-15268', 
    'sphinx-doc__sphinx-9281', 
    'sympy__sympy-21930', 
    'django__django-11133', 
    'django__django-10973', 
    'django__django-13810', 
    'django__django-16032', 
    'sympy__sympy-14976', 
    'django__django-11490', 
    'django__django-15930', 
    'sympy__sympy-12419', 
    'sympy__sympy-24539', 
    'pydata__xarray-6599', 
    'sympy__sympy-21847', 
    'django__django-15695', 
    'sympy__sympy-22080', 
    'django__django-13658', 
    'django__django-16333', 
    'sympy__sympy-14711', 
    'sympy__sympy-19637'
]